var transl8 = transl8 || {};
transl8.en = {
    "ui_please_select": "Please select",
    "ui_username": "User Name",
    "ui_password": "Password",
    "ui_entries": "Entries",
    "ui_total": "Total",
    "footer_privacy": "Privacy",
    "backend_missing": "Connection to the arachne backend cannot not be established.",
    "default": "An unknown error has occured.",
    "ui_filter_plural": "Filters",
    "pick_an_item": "Pick an item",
    "form_save": "Save",
    "form_reset": "Reset",
    "picker_perform_search": "Perform a search to pick an item",
    "picker_no_result": "No items found",
    "results": "Results",
    "everything_fine": "Everything fine",
    "components.message.contact": "Please contact CONTACT if the errors persist.",
    "ui_login": "login",
    "ui_login_failed": "Login failed. Please try again!",
    "ui_page": "Page",
    "ui_previous": "Previous",
    "ui_next": "Next",
    "contact_success": "Message has been sent. We will contact you by email as soon as possible.",
    "navbar_sign_up": "Sign Up",
    "footer_licensed_under": "Licensed under",
    "footer_bugs_to": "Report bugs to",
    "contact_first_surname": "First name & surname",
    "ui_subject": "Subject",
    "ui_message": "Message",
    "ui_nomachine": "I'm not a machine",
    "navbar_placeholder_search": "Search for",
    "ui_send": "Send",
    "ui_placeholder_search": "Search",
    "ui_showall": "Show all",
    "navbar_sign_in": "Sign In",
    "test": "from \"shared\"",
    "navbar_sign_out": "Sign Out",
    "navbar_old_searches": "Recently searched for",
    "ui_back": "Back",
    "ui_add_value": "Add value",
    "ui_add_tag": "Add tag",
    "ui_add_name": "Add name",
    "ui_add_language": "Add language",
    "navbar_this_scope": "This Scope",
    "navbar_leave_scope": "Leave Search Scope"
}
