var transl8 = transl8 || {};
transl8['de'] = {
    "ui_username": "Benutzername",
    "ui_please_select": "Bitte auswählen",
    "ui_password": "Passwort",
    "ui_entries": "Einträge",
    "ui_total": "Insgesamt",
    "footer_privacy": "Datenschutz",
    "backend_missing": "Die Verbindung zum Arachne-Server konnte nicht hergestellt werden.",
    "default": "Ein unbekannter Fehler ist aufgetreten.",
    "ui_filter_plural": "Filter",
    "pick_an_item": "Wählen Sie einen Eintrag",
    "form_save": "Speichern",
    "form_reset": "Zurücksetzen",
    "picker_perform_search": "Starten Sie eine Suchanfrage, um einen Eintrag auszuwählen",
    "picker_no_result": "Keine Einträge gefunden",
    "results": "Ergebnisse",
    "everything_fine": "Alles in bester Ordnung",
    "components.message.contact": "Bitte kontaktieren Sie CONTACT, sollte der Fehler weiterhin auftreten.",
    "ui_login": "Anmeldung",
    "ui_login_successfull": "Anmeldung erfolgreich. Nutzer",
    "ui_login_failed": "Anmeldung fehlgeschlagen, bitte erneut versuchen!",
    "ui_page": "Seite",
    "ui_previous": "Zurück",
    "ui_next": "Weiter",
    "navbar_placeholder_search": "Neue Suche",
    "contact_success": "Nachricht versendet. Sie sollten in Kürze eine eMail von uns erhalten.",
    "navbar_sign_up": "Registrieren",
    "footer_licensed_under": "Lizensiert unter",
    "footer_bugs_to": "Fehlermeldungen bitte an",
    "contact_first_surname": "Vor- & Nachname",
    "ui_subject": "Betreff",
    "ui_message": "Nachricht",
    "ui_nomachine": "Ich bin keine Maschine",
    "ui_send": "Senden",
    "ui_placeholder_search": "Suche",
    "ui_showall": "Alle anzeigen",
    "navbar_sign_in": "Anmelden",
    "test": "von \"shared\"",
    "navbar_sign_out": "Abmelden",
    "navbar_old_searches": "Ältere Suchen",
    "ui_back": "Zurück",
    "ui_add_value": "Wert hinzufügen",
    "ui_add_tag": "Tag hinzufügen",
    "ui_add_name": "Namen hinzufügen",
    "ui_add_language": "Sprache hinzufügen",
    "navbar_this_scope": "Dieser Suchbereich",
    "navbar_leave_scope": "Suchbereich verlassen"
};
